
networks:
  homeassistant:
    external: true

services:
  hass_apartement:
    build: .
    container_name: hass_apartement  # Name your container
    command: python main.py # Command to run your script
    volumes:
      - ./logs:/app/logs
    networks:
      - homeassistant