version: '3.8'  # Define the version of Docker Compose

services:
  hass_apartement:
    build: .
    container_name: hass_apartement  # Name your container
    command: python main.py # Command to run your script
    volumes:
      - ./logs:/app/logs